<%@ include file="../common/header.jspf" %>
<%@ include file="../common/public-nav.jspf" %>
<main>
    <section class="public-hero py-5"><div class="container py-5 position-relative" style="z-index:1"><div class="row align-items-center g-5"><div class="col-lg-7"><div class="page-eyebrow text-white-50">Event operations, simplified</div><h1 class="display-4 fw-bold mt-2 mb-3">Make every event feel effortless.</h1><p class="lead text-white-50 mb-4">Discover memorable experiences, manage registrations, and keep every attendee in the loop from one calm, dependable workspace.</p><div class="d-flex flex-wrap gap-2"><a class="btn btn-light btn-lg px-4" href="${ctx}/events">Explore events <i class="bi bi-arrow-right ms-2"></i></a><a class="btn btn-outline-light btn-lg px-4" href="${ctx}/register">Host an event</a></div></div><div class="col-lg-5"><div class="panel text-dark p-4 position-relative"><div class="d-flex justify-content-between align-items-center mb-4"><span class="status-badge badge-soft-success">● Platform live</span><span class="small muted">MySQL · JDBC</span></div><h3 class="fw-bold">One clear view of your event world.</h3><p class="muted">Role-aware workspaces for admins, organizers, and attendees.</p><div class="row g-2 mt-3"><div class="col-6"><div class="bg-light rounded p-3"><div class="h4 fw-bold mb-0">3</div><small class="muted">Role workspaces</small></div></div><div class="col-6"><div class="bg-light rounded p-3"><div class="h4 fw-bold mb-0">24/7</div><small class="muted">Event visibility</small></div></div></div></div></div></div></div></section>
    <section class="py-5"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><div class="page-eyebrow">Coming up</div><h2 class="page-title">Find your next room to be in.</h2><p class="muted mb-0">Approved events, ready for registration.</p></div><a href="${ctx}/events" class="btn btn-soft">View catalogue <i class="bi bi-arrow-right ms-1"></i></a></div><div class="row g-4"><c:forEach var="event" items="${events}" begin="0" end="2"><div class="col-md-4"><div class="event-card"><c:choose><c:when test="${not empty event.bannerUrl}"><img class="event-cover" src="${event.bannerUrl}" alt="Event cover"></c:when><c:otherwise><div class="event-cover-placeholder"><i class="bi bi-calendar-event display-5"></i></div></c:otherwise></c:choose><div class="p-3"><div class="d-flex justify-content-between gap-2"><span class="status-badge badge-soft-primary"><c:out value="${event.category}"/></span><small class="muted"><c:out value="${event.eventDate}"/></small></div><h5 class="fw-bold mt-3 mb-2"><c:out value="${event.title}"/></h5><p class="muted small mb-3"><i class="bi bi-geo-alt me-1"></i><c:out value="${event.venue}"/></p><a href="${ctx}/events/view?id=${event.id}" class="stretched-link"></a></div></div></div></c:forEach><c:if test="${empty events}"><div class="col-12"><div class="empty-state panel">No approved events yet. Check back soon.</div></div></c:if></div></div></section>
    <section class="py-5 bg-white border-top"><div class="container"><div class="row g-4"><div class="col-md-4"><i class="bi bi-shield-check fs-2 text-primary"></i><h5 class="fw-bold mt-3">Built for trust</h5><p class="muted">Session authentication, role filters, and server-side validation protect every workflow.</p></div><div class="col-md-4"><i class="bi bi-diagram-3 fs-2 text-primary"></i><h5 class="fw-bold mt-3">Built for clarity</h5><p class="muted">A simple Servlet → Service → DAO structure that stays easy to explain and maintain.</p></div><div class="col-md-4"><i class="bi bi-bar-chart fs-2 text-primary"></i><h5 class="fw-bold mt-3">Built for momentum</h5><p class="muted">Dashboards, ticket inventory, approvals, and updates stay visible in one place.</p></div></div></div></section>
</main>
<footer class="container footer">EventFlow · A focused event management platform.</footer>
<%@ include file="../common/public-end.jspf" %>
